    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.8
            uses: actions/setup-python@v1
            with:
              python-version: 3.8
          - name: Cache pip
            uses: actions/cache@v1
            with:
                path: ~/.cache/pip # This path is specific to Ubuntu
                # Look to see if there is a cache hit for the corresponding requirements file
                key: ${{ runner.os }}-pip-${{ hashFiles('classroom_requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-
                    ${{ runner.os }}- 
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r classroom_requirements.txt
          - name: Display Python version
            run: python -c "import sys; print(sys.version)"
          - uses: education/autograding@v1
